ALTER TABLE "inventory_items" ADD COLUMN "keychainOffsetX" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "inventory_items" ADD COLUMN "keychainOffsetY" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "inventory_items" ADD COLUMN "keychainOffsetZ" DOUBLE PRECISION NOT NULL DEFAULT 0;
